"""
Pydantic Schemas for Phase 3: AI-Powered Financial Intelligence Layer.
"""
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class EvidenceRecord(BaseModel):
    """Traceable individual record cited in an AI explanation."""
    record_type: str = Field(..., description="ORDER | PAYMENT | SETTLEMENT | BANK_TRANSACTION | SHIPMENT | REFUND | LEDGER")
    record_id: str = Field(..., description="Verified primary ID of record")
    status: Optional[str] = Field(None, description="Current verification or processing status")
    amount_inr: Optional[str] = Field(None, description="Formatted INR amount if applicable")
    verified: bool = Field(True, description="True if record exists and is verified in database")
    discrepancy: Optional[str] = Field(None, description="Identified issue or discrepancy note if any")


class CaseExplanationResponse(BaseModel):
    """Structured AI explanation for a specific financial exception case."""
    case_id: str
    exception_type: str
    risk_level: str
    value_at_risk_inr: str
    summary: str = Field(..., description="High-level executive summary")
    what_happened: str = Field(..., description="Chronological facts of transaction journey")
    why_flagged: str = Field(..., description="Specific rule or condition that triggered the alert")
    financial_impact: str = Field(..., description="Potential exposure, dispute, refund, or ledger risk")
    suggested_owner: str = Field(..., description="Operations | Finance | Support")
    suggested_owner_reason: str = Field(..., description="Deterministic reason for ownership assignment")
    recommended_actions: List[str] = Field(..., description="Concrete step-by-step investigation/resolution steps (read-only advisory)")
    verified_facts: Dict[str, Any] = Field(..., description="Raw deterministic facts extracted from database")
    evidence_ids: List[str] = Field(..., description="Strictly validated record IDs referenced in the case")
    evidence_records: List[EvidenceRecord] = Field(default_factory=list, description="Structured verified evidence citations")
    confidence_note: str = Field(..., description="Statement of deterministic grounding")
    is_fallback: bool = Field(False, description="True if generated by deterministic fallback engine")


class AssistantQueryRequest(BaseModel):
    """Query payload for the Settlement Q&A assistant."""
    query: str = Field(..., min_length=2, max_length=500, description="Finance or reconciliation question")


class FinancialBreakdown(BaseModel):
    """Deterministic financial breakdown for settlement/cash queries."""
    gross_amount_inr: Optional[str] = None
    fee_amount_inr: Optional[str] = None
    tax_amount_inr: Optional[str] = None
    refund_adjustment_inr: Optional[str] = None
    other_adjustment_inr: Optional[str] = None
    expected_net_inr: Optional[str] = None
    reported_or_bank_inr: Optional[str] = None
    variance_inr: Optional[str] = None
    status: Optional[str] = None


class AssistantQueryResponse(BaseModel):
    """Structured response from the Settlement Q&A assistant."""
    query: str
    detected_intent: str = Field(..., description="Identified supported finance intent")
    answer: str = Field(..., description="Plain-language, evidence-grounded answer")
    explanation: str = Field(..., description="Detailed explanation of the financial context")
    breakdown: Optional[FinancialBreakdown] = Field(None, description="Pre-calculated financial breakdown if applicable")
    verified_facts: Dict[str, Any] = Field(default_factory=dict, description="Verified facts from the database")
    evidence_records: List[EvidenceRecord] = Field(default_factory=list, description="Traceable linked records")
    recommended_actions: List[str] = Field(default_factory=list, description="Suggested next actions for merchant team")
    is_fallback: bool = Field(False, description="True if generated via deterministic fallback")
    disclaimer: str = Field(
        default="AI explains financial data based on verified database records. All financial actions require human approval.",
        description="Standard safety disclaimer"
    )


class DailyExceptionSummaryResponse(BaseModel):
    """Executive daily finance exception summary."""
    as_of: str
    total_unresolved_cases: int
    total_value_at_risk_inr: str
    critical_cases_count: int
    high_cases_count: int
    medium_cases_count: int
    low_cases_count: int
    summary_text: str = Field(..., description="Executive narrative summary grounded in verified aggregates")
    highest_priority_case_id: Optional[str] = None
    highest_priority_case_summary: Optional[str] = None
    top_recommended_actions: List[str] = Field(default_factory=list)
    is_fallback: bool = Field(False)
